apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sre-technical-challenge.fullname" . }}-migration
  labels:
    {{- include "sre-technical-challenge.migrationLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "sre-technical-challenge.migrationSelectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migration
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["migrate"]
        env:
        {{- if .Values.env }}
        {{- tpl .Values.env . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}

